"""
Exercise Page

Displays the personalized workout plan
generated by the Exercise Agent.
"""

import streamlit as st

st.set_page_config(
    page_title="Exercise Plan",
    page_icon="🏋️",
    layout="wide"
)

st.title("🏋️ Personalized Exercise Plan")

st.markdown("---")

######################################################

if "report" not in st.session_state:

    st.warning(
        "Please generate your health report first."
    )

    st.stop()

######################################################

report = st.session_state["report"]

exercise_plan = report["exercise"]

######################################################

st.success("Your AI-Generated 7-Day Workout Plan")

st.markdown(exercise_plan)

######################################################

st.markdown("---")

st.subheader("📅 Weekly Workout Tracker")

days = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
]

completed = 0

for day in days:
    if st.checkbox(f"✅ {day}", key=day):
        completed += 1

progress = completed / len(days)

st.progress(progress)

st.write(f"Workout Completion: **{completed}/7 Days**")

######################################################

if completed == 7:

    st.success("🎉 Amazing! You completed every workout this week!")

elif completed >= 5:

    st.info("👏 Great job! You're staying consistent.")

elif completed >= 3:

    st.warning("👍 Keep going! You're making progress.")

else:

    st.error("💪 Try to stay active this week!")

######################################################

st.markdown("---")

st.subheader("👣 Daily Step Counter")

steps = st.number_input(

    "Steps Walked Today",

    min_value=0,

    max_value=50000,

    value=5000,

    step=500

)

goal = 10000

st.progress(min(steps / goal, 1.0))

st.write(f"Today's Steps: **{steps} / {goal}**")

if steps >= goal:

    st.success("🎉 Daily step goal achieved!")

else:

    st.info(f"{goal - steps} more steps to reach today's goal.")

######################################################

st.markdown("---")

st.subheader("😴 Sleep Tracker")

sleep = st.slider(

    "Hours Slept",

    min_value=0,

    max_value=12,

    value=7

)

if sleep >= 8:

    st.success("Excellent sleep!")

elif sleep >= 6:

    st.info("Good sleep. Aim for 7–9 hours consistently.")

else:

    st.warning("Try to improve your sleep duration.")

######################################################

st.markdown("---")

st.subheader("📝 Workout Notes")

notes = st.text_area(

    "Write today's workout experience",

    placeholder="Example: Felt stronger during cardio..."
)

if st.button("Save Workout Notes"):

    st.success("Workout notes saved successfully!")

######################################################

st.markdown("---")

st.caption("AI Healthcare Nutrition Coach")