"""
Meal Plan Page

Displays the personalized meal plan
generated by the Meal Planner Agent.
"""

import streamlit as st

st.set_page_config(
    page_title="Meal Planner",
    page_icon="🍽️",
    layout="wide"
)

st.title("🍽️ Personalized Meal Plan")

st.markdown("---")

######################################################

if "report" not in st.session_state:

    st.warning(
        "Please generate your health report first."
    )

    st.stop()

######################################################

report = st.session_state["report"]

meal_plan = report["meal_plan"]

######################################################

st.success("Your Personalized AI Meal Plan")

st.markdown(meal_plan)

######################################################

st.markdown("---")

st.subheader("🍎 Meal Completion Tracker")

breakfast = st.checkbox("Breakfast Completed")

morning_snack = st.checkbox("Morning Snack Completed")

lunch = st.checkbox("Lunch Completed")

evening_snack = st.checkbox("Evening Snack Completed")

dinner = st.checkbox("Dinner Completed")

######################################################

completed = sum([
    breakfast,
    morning_snack,
    lunch,
    evening_snack,
    dinner
])

progress = completed / 5

st.progress(progress)

st.write(f"Meals Completed: **{completed}/5**")

######################################################

if completed == 5:

    st.success("🎉 Excellent! You completed all your meals today.")

elif completed >= 3:

    st.info("👍 Great! You're staying on track.")

else:

    st.warning("Try not to skip meals. Consistency is important.")

######################################################

st.markdown("---")

st.subheader("💧 Water Intake")

water = st.slider(

    "Liters of Water",

    min_value=0.0,

    max_value=5.0,

    value=2.0,

    step=0.1

)

if water >= 2.5:

    st.success("Excellent hydration!")

elif water >= 1.5:

    st.info("You're doing well. Try drinking a little more.")

else:

    st.warning("Increase your water intake today.")

######################################################

st.markdown("---")

st.subheader("📝 Daily Notes")

notes = st.text_area(

    "Write today's food notes",

    placeholder="Example: Felt energetic after lunch..."

)

if st.button("Save Notes"):

    st.success("Notes saved successfully!")

######################################################

st.markdown("---")

st.caption("AI Healthcare Nutrition Coach")